jobs:
  build:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build and Test
      run: MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
        --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
        mvn -B verify -Dmongodb.version="${{ matrix.mongodb-version }}" -Dkarate.options="${{
        matrix.karate-options }}"
    strategy:
      matrix:
        include:
        - mongodb-version: 4.2
        - mongodb-version: 4.4
        - mongodb-version: 5.0
        - deploy: true
          mongodb-version: 6.0
        - mongodb-version: 7.0
    timeout-minutes: 20
name: Build pull request
on:
  repository_dispatch:
    types: trigger-ga___pullrequests.yml
